<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<PackageId>Krypt.Core</PackageId>
		<Version>1.0.0</Version>
		<Authors>Yel0w</Authors>
		<Company>PikminTea</Company>
		<PackageIcon>icon.png</PackageIcon>

		<Description>encryption library for .NET</Description>
		<PackageTags>cryptography encryption security</PackageTags>

		<RepositoryUrl>https://github.com/Yel0w08/Krypt</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	 <PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
<ItemGroup>
	<None Include="icon.png" Pack="true" PackagePath="" />
	<None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>